services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\AcademicProjects\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*.php'

  FGTCLB\AcademicProjects\Domain\Repository\ProjectRepository:
    public: true

  FGTCLB\AcademicPrograms\DataProcessing\ProjectProcessor:
    tags:
      - {
          name: 'data.processor',
          identifier: 'project-data',
          label: 'Project Processor'
        }
